/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jogotetris.GUI;

import java.awt.Frame;
import java.awt.geom.RoundRectangle2D;

/**
 *
 * @author senti
 */
public class ClassicGameLose extends javax.swing.JDialog {
    public Frame parent;
    public String pontos;
    /**
     * Creates new form ClassicGameLose
     */
    public ClassicGameLose(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        setLocation(285,111);
        this.setUndecorated(true);
        initComponents();
        setShape(new RoundRectangle2D.Double(0,0,getWidth(), getHeight(),20,20));
        labelPoints.setText("OLA");
    }
    public ClassicGameLose(java.awt.Frame parent, boolean modal,int pontos){
        super(parent, modal);
        this.parent = parent;
        setLocation(285,111);
        this.setUndecorated(true);
        initComponents();
        setShape(new RoundRectangle2D.Double(0,0,getWidth(), getHeight(),20,20));
        System.out.println(pontos);
         labelPoints.setText(""+pontos);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBg1 = new jogotetris.GUI.Componentes.JPanelBg();
        jPanelBg2 = new jogotetris.GUI.Componentes.JPanelBg();
        JPanelContainerPoints = new jogotetris.GUI.Componentes.JPanelBg();
        JPanelPoints = new jogotetris.GUI.Componentes.JPanelBg();
        labelPoints = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnStart1 = new jogotetris.GUI.Componentes.BtnStart();
        btnStart2 = new jogotetris.GUI.Componentes.BtnStart();
        jPanelBg3 = new jogotetris.GUI.Componentes.JPanelBg();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanelBg1.setBorderColor(new java.awt.Color(0, 24, 41));
        jPanelBg1.setColor(new java.awt.Color(0, 24, 41));

        jPanelBg2.setBorderColor(new java.awt.Color(0, 24, 41));
        jPanelBg2.setColor(new java.awt.Color(0, 24, 41));
        jPanelBg2.setRadius(20);

        JPanelContainerPoints.setBorderColor(new java.awt.Color(18, 48, 65));
        JPanelContainerPoints.setBorderWidth(0);
        JPanelContainerPoints.setColor(new java.awt.Color(18, 48, 65));
        JPanelContainerPoints.setRadius(20);

        JPanelPoints.setBorderColor(new java.awt.Color(44, 69, 84));
        JPanelPoints.setBorderWidth(0);
        JPanelPoints.setColor(new java.awt.Color(44, 69, 84));
        JPanelPoints.setMaximumSize(new java.awt.Dimension(65, 58));
        JPanelPoints.setMinimumSize(new java.awt.Dimension(65, 58));
        JPanelPoints.setRadius(20);

        labelPoints.setFont(new java.awt.Font("Gill Sans Ultra Bold", 1, 18)); // NOI18N
        labelPoints.setForeground(new java.awt.Color(228, 229, 214));
        labelPoints.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPoints.setText("0");

        javax.swing.GroupLayout JPanelPointsLayout = new javax.swing.GroupLayout(JPanelPoints);
        JPanelPoints.setLayout(JPanelPointsLayout);
        JPanelPointsLayout.setHorizontalGroup(
            JPanelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPoints, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
        );
        JPanelPointsLayout.setVerticalGroup(
            JPanelPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelPoints, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        jLabel2.setBackground(new java.awt.Color(228, 229, 214));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(228, 229, 214));
        jLabel2.setText("Points");

        javax.swing.GroupLayout JPanelContainerPointsLayout = new javax.swing.GroupLayout(JPanelContainerPoints);
        JPanelContainerPoints.setLayout(JPanelContainerPointsLayout);
        JPanelContainerPointsLayout.setHorizontalGroup(
            JPanelContainerPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelContainerPointsLayout.createSequentialGroup()
                .addGroup(JPanelContainerPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelContainerPointsLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(JPanelPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelContainerPointsLayout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel2)))
                .addGap(37, 37, 37))
        );
        JPanelContainerPointsLayout.setVerticalGroup(
            JPanelContainerPointsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelContainerPointsLayout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(JPanelPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        btnStart1.setForeground(new java.awt.Color(228, 229, 214));
        btnStart1.setText("back");
        btnStart1.setBorderColor(new java.awt.Color(228, 229, 214));
        btnStart1.setColor(new java.awt.Color(0, 24, 41));
        btnStart1.setColorOver(new java.awt.Color(228, 229, 214));
        btnStart1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart1.setRadius(20);
        btnStart1.setSizeBorder(2);
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        btnStart2.setForeground(new java.awt.Color(0, 24, 41));
        btnStart2.setText("play again");
        btnStart2.setBorderColor(new java.awt.Color(228, 229, 214));
        btnStart2.setColorOver(new java.awt.Color(0, 24, 41));
        btnStart2.setFixColor(new java.awt.Color(0, 24, 41));
        btnStart2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart2.setRadius(20);
        btnStart2.setSizeBorder(2);
        btnStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBg2Layout = new javax.swing.GroupLayout(jPanelBg2);
        jPanelBg2.setLayout(jPanelBg2Layout);
        jPanelBg2Layout.setHorizontalGroup(
            jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg2Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanelBg2Layout.createSequentialGroup()
                        .addComponent(btnStart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JPanelContainerPoints, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(84, 84, 84))
        );
        jPanelBg2Layout.setVerticalGroup(
            jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(JPanelContainerPoints, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 237, Short.MAX_VALUE)
                .addGroup(jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56))
        );

        jPanelBg3.setBorderColor(new java.awt.Color(18, 48, 65));
        jPanelBg3.setColor(new java.awt.Color(18, 48, 65));
        jPanelBg3.setRadius(20);

        jLabel1.setBackground(new java.awt.Color(228, 229, 214));
        jLabel1.setFont(new java.awt.Font("Gill Sans Nova Cond Ultra Bold", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(228, 229, 214));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("OH, NO... YOU LOSE");

        javax.swing.GroupLayout jPanelBg3Layout = new javax.swing.GroupLayout(jPanelBg3);
        jPanelBg3.setLayout(jPanelBg3Layout);
        jPanelBg3Layout.setHorizontalGroup(
            jPanelBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBg3Layout.setVerticalGroup(
            jPanelBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg3Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelBg1Layout = new javax.swing.GroupLayout(jPanelBg1);
        jPanelBg1.setLayout(jPanelBg1Layout);
        jPanelBg1Layout.setHorizontalGroup(
            jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanelBg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jPanelBg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        jPanelBg1Layout.setVerticalGroup(
            jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart2ActionPerformed
        // TODO add your handling code here:
        ClassicGameMode classic = new ClassicGameMode(parent,true);
        classic.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnStart2ActionPerformed

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnStart1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ClassicGameLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ClassicGameLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ClassicGameLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ClassicGameLose.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ClassicGameLose dialog = new ClassicGameLose(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jogotetris.GUI.Componentes.JPanelBg JPanelContainerPoints;
    private jogotetris.GUI.Componentes.JPanelBg JPanelPoints;
    private jogotetris.GUI.Componentes.BtnStart btnStart1;
    private jogotetris.GUI.Componentes.BtnStart btnStart2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg1;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg2;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg3;
    private javax.swing.JLabel labelPoints;
    // End of variables declaration//GEN-END:variables
}
