/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jogotetris.GUI;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.geom.RoundRectangle2D;
import java.util.Objects;
import java.util.Timer;
import javax.swing.JLabel;
import jogotetris.App.MoveGame;
import jogotetris.App.MoveGameMultiplayer;

/**
 *
 * @author senti
 */
public class MultiplayerGameMode extends javax.swing.JDialog implements KeyListener {
    public int gameOver  = 0;
    public Timer timerGame = new Timer();
    /**
     * Creates new form MultiplayerGameMode
     */
    @Override
    public void keyTyped(KeyEvent e) {
    }
    
    @Override
    public void keyReleased(KeyEvent e) {
       
        
    }
    @Override
    public void keyPressed(KeyEvent e) {
        int keyCode = e.getKeyCode();
        switch (keyCode) {
            case KeyEvent.VK_UP:
                tetrisGame2.rotate();   
                tetrisGame2.repaint();
                break;
            case KeyEvent.VK_DOWN:
                tetrisGame2.moveDown();
                tetrisGame2.repaint();
                break;
            case KeyEvent.VK_LEFT:
                tetrisGame2.moveLeft();
                tetrisGame1.repaint();
                break;
            case KeyEvent.VK_RIGHT:
                tetrisGame2.moveRight();
                tetrisGame2.repaint();
                break;
            case KeyEvent.VK_SPACE:
                tetrisGame2.fallDown();
                tetrisGame2.repaint();
                break;
            case KeyEvent.VK_W:
                tetrisGame1.rotate();
                tetrisGame1.repaint();
                break;
            case KeyEvent.VK_S:
                tetrisGame1.moveDown();
                tetrisGame1.repaint();
                break;
            case KeyEvent.VK_D:
                tetrisGame1.moveRight();
                tetrisGame1.repaint();
                break;
            case KeyEvent.VK_A:
                tetrisGame1.moveLeft();
                tetrisGame1.repaint();
                break;
            case KeyEvent.VK_Q:
                tetrisGame1.fallDown();
                tetrisGame1.repaint();
                break;
            default:
                break;
        }
                    
    }
    public MultiplayerGameMode(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        setLocation(285,111);
        this.setUndecorated(true);
        initComponents();
        tetrisGame1.resize(14, 11);
        tetrisGame1.player = 1;
        tetrisGame2.resize(14, 11);
        tetrisGame2.player = 2;
        setShape(new RoundRectangle2D.Double(0,0,getWidth(), getHeight(),20,20));
        tetrisGame1.addKeyListener(this);
        startGame(1000,1000);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBg1 = new jogotetris.GUI.Componentes.JPanelBg();
        jPanelBg2 = new jogotetris.GUI.Componentes.JPanelBg();
        tetrisGame1 = new jogotetris.App.TetrisGame();
        jPanelBg3 = new jogotetris.GUI.Componentes.JPanelBg();
        tetrisGame2 = new jogotetris.App.TetrisGame();
        jPanelBg4 = new jogotetris.GUI.Componentes.JPanelBg();
        jPanelBg5 = new jogotetris.GUI.Componentes.JPanelBg();
        jPanelBg7 = new jogotetris.GUI.Componentes.JPanelBg();
        JPanelContainerPointsPlayer1 = new jogotetris.GUI.Componentes.JPanelBg();
        JLabelPointsPlayer1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanelBg6 = new jogotetris.GUI.Componentes.JPanelBg();
        jPanelBg9 = new jogotetris.GUI.Componentes.JPanelBg();
        JPanelContainerPointsPlayer2 = new jogotetris.GUI.Componentes.JPanelBg();
        JLabelPointsPlayer2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        btnStart1 = new jogotetris.GUI.Componentes.BtnStart();
        btnStart2 = new jogotetris.GUI.Componentes.BtnStart();
        btnClose1 = new jogotetris.GUI.Componentes.BtnClose();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanelBg1.setBorderColor(new java.awt.Color(255, 255, 255));
        jPanelBg1.setColor(new java.awt.Color(0, 24, 41));

        jPanelBg2.setBorderColor(new java.awt.Color(18, 48, 65));
        jPanelBg2.setColor(new java.awt.Color(18, 48, 65));

        javax.swing.GroupLayout tetrisGame1Layout = new javax.swing.GroupLayout(tetrisGame1);
        tetrisGame1.setLayout(tetrisGame1Layout);
        tetrisGame1Layout.setHorizontalGroup(
            tetrisGame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        tetrisGame1Layout.setVerticalGroup(
            tetrisGame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBg2Layout = new javax.swing.GroupLayout(jPanelBg2);
        jPanelBg2.setLayout(jPanelBg2Layout);
        jPanelBg2Layout.setHorizontalGroup(
            jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tetrisGame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBg2Layout.setVerticalGroup(
            jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tetrisGame1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBg3.setBorderColor(new java.awt.Color(18, 48, 65));
        jPanelBg3.setColor(new java.awt.Color(18, 48, 65));

        javax.swing.GroupLayout tetrisGame2Layout = new javax.swing.GroupLayout(tetrisGame2);
        tetrisGame2.setLayout(tetrisGame2Layout);
        tetrisGame2Layout.setHorizontalGroup(
            tetrisGame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 288, Short.MAX_VALUE)
        );
        tetrisGame2Layout.setVerticalGroup(
            tetrisGame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanelBg3Layout = new javax.swing.GroupLayout(jPanelBg3);
        jPanelBg3.setLayout(jPanelBg3Layout);
        jPanelBg3Layout.setHorizontalGroup(
            jPanelBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tetrisGame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBg3Layout.setVerticalGroup(
            jPanelBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tetrisGame2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBg4.setBorderColor(new java.awt.Color(0, 24, 41));
        jPanelBg4.setColor(new java.awt.Color(0, 24, 41));

        jPanelBg5.setBorderColor(new java.awt.Color(18, 48, 65));
        jPanelBg5.setColor(new java.awt.Color(18, 48, 65));

        jPanelBg7.setBorderColor(new java.awt.Color(44, 69, 84));
        jPanelBg7.setColor(new java.awt.Color(44, 69, 84));
        jPanelBg7.setRadius(20);

        JPanelContainerPointsPlayer1.setBorderColor(new java.awt.Color(128, 128, 128));
        JPanelContainerPointsPlayer1.setRadius(20);

        JLabelPointsPlayer1.setBackground(new java.awt.Color(255, 255, 255));
        JLabelPointsPlayer1.setFont(new java.awt.Font("Gill Sans Nova Cond Ultra Bold", 0, 18)); // NOI18N
        JLabelPointsPlayer1.setForeground(new java.awt.Color(255, 255, 255));
        JLabelPointsPlayer1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPointsPlayer1.setText("0");
        JLabelPointsPlayer1.setToolTipText("");

        javax.swing.GroupLayout JPanelContainerPointsPlayer1Layout = new javax.swing.GroupLayout(JPanelContainerPointsPlayer1);
        JPanelContainerPointsPlayer1.setLayout(JPanelContainerPointsPlayer1Layout);
        JPanelContainerPointsPlayer1Layout.setHorizontalGroup(
            JPanelContainerPointsPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelContainerPointsPlayer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelPointsPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelContainerPointsPlayer1Layout.setVerticalGroup(
            JPanelContainerPointsPlayer1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelContainerPointsPlayer1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelPointsPlayer1, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PLAYER 1");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("points");

        javax.swing.GroupLayout jPanelBg7Layout = new javax.swing.GroupLayout(jPanelBg7);
        jPanelBg7.setLayout(jPanelBg7Layout);
        jPanelBg7Layout.setHorizontalGroup(
            jPanelBg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg7Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(JPanelContainerPointsPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanelBg7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBg7Layout.setVerticalGroup(
            jPanelBg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JPanelContainerPointsPlayer1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBg5Layout = new javax.swing.GroupLayout(jPanelBg5);
        jPanelBg5.setLayout(jPanelBg5Layout);
        jPanelBg5Layout.setHorizontalGroup(
            jPanelBg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelBg7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBg5Layout.setVerticalGroup(
            jPanelBg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg5Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jPanelBg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jPanelBg6.setBorderColor(new java.awt.Color(18, 48, 65));
        jPanelBg6.setBorderWidth(0);
        jPanelBg6.setColor(new java.awt.Color(18, 48, 65));

        jPanelBg9.setBorderColor(new java.awt.Color(44, 69, 84));
        jPanelBg9.setColor(new java.awt.Color(44, 69, 84));
        jPanelBg9.setRadius(20);

        JPanelContainerPointsPlayer2.setBorderColor(new java.awt.Color(128, 128, 128));
        JPanelContainerPointsPlayer2.setRadius(20);

        JLabelPointsPlayer2.setFont(new java.awt.Font("Gill Sans Nova Cond Ultra Bold", 0, 18)); // NOI18N
        JLabelPointsPlayer2.setForeground(new java.awt.Color(255, 255, 255));
        JLabelPointsPlayer2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        JLabelPointsPlayer2.setText("0");

        javax.swing.GroupLayout JPanelContainerPointsPlayer2Layout = new javax.swing.GroupLayout(JPanelContainerPointsPlayer2);
        JPanelContainerPointsPlayer2.setLayout(JPanelContainerPointsPlayer2Layout);
        JPanelContainerPointsPlayer2Layout.setHorizontalGroup(
            JPanelContainerPointsPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelContainerPointsPlayer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelPointsPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                .addContainerGap())
        );
        JPanelContainerPointsPlayer2Layout.setVerticalGroup(
            JPanelContainerPointsPlayer2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelContainerPointsPlayer2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JLabelPointsPlayer2, javax.swing.GroupLayout.DEFAULT_SIZE, 42, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText(" PLAYER 2");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("points");

        javax.swing.GroupLayout jPanelBg9Layout = new javax.swing.GroupLayout(jPanelBg9);
        jPanelBg9.setLayout(jPanelBg9Layout);
        jPanelBg9Layout.setHorizontalGroup(
            jPanelBg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg9Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(JPanelContainerPointsPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelBg9Layout.createSequentialGroup()
                .addGroup(jPanelBg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBg9Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelBg9Layout.setVerticalGroup(
            jPanelBg9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(JPanelContainerPointsPlayer2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanelBg6Layout = new javax.swing.GroupLayout(jPanelBg6);
        jPanelBg6.setLayout(jPanelBg6Layout);
        jPanelBg6Layout.setHorizontalGroup(
            jPanelBg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg6Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jPanelBg9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBg6Layout.setVerticalGroup(
            jPanelBg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg6Layout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addComponent(jPanelBg9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        btnStart1.setForeground(new java.awt.Color(255, 255, 255));
        btnStart1.setText("PAUSE");
        btnStart1.setBorderColor(new java.awt.Color(255, 255, 255));
        btnStart1.setColor(new java.awt.Color(0, 24, 41));
        btnStart1.setFixColor(new java.awt.Color(255, 255, 255));
        btnStart1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart1.setRadius(25);
        btnStart1.setSizeBorder(2);
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        btnStart2.setForeground(new java.awt.Color(255, 255, 255));
        btnStart2.setText("END GAME");
        btnStart2.setBorderColor(new java.awt.Color(255, 255, 255));
        btnStart2.setColor(new java.awt.Color(0, 24, 41));
        btnStart2.setFixColor(new java.awt.Color(255, 255, 255));
        btnStart2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnStart2.setPreferredSize(new java.awt.Dimension(78, 40));
        btnStart2.setRadius(25);
        btnStart2.setSizeBorder(2);
        btnStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBg4Layout = new javax.swing.GroupLayout(jPanelBg4);
        jPanelBg4.setLayout(jPanelBg4Layout);
        jPanelBg4Layout.setHorizontalGroup(
            jPanelBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg4Layout.createSequentialGroup()
                .addComponent(jPanelBg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanelBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg4Layout.createSequentialGroup()
                        .addGroup(jPanelBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnStart2, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                            .addComponent(btnStart1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(40, 40, 40))
                    .addComponent(jPanelBg6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );
        jPanelBg4Layout.setVerticalGroup(
            jPanelBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg4Layout.createSequentialGroup()
                .addComponent(jPanelBg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jPanelBg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnClose1.setForeground(new java.awt.Color(255, 0, 0));
        btnClose1.setToolTipText("");
        btnClose1.setBorderColor(new java.awt.Color(51, 51, 51));
        btnClose1.setColor(new java.awt.Color(51, 51, 51));
        btnClose1.setColorOver(new java.awt.Color(255, 102, 102));
        btnClose1.setFont(new java.awt.Font("Arial Narrow", 0, 8)); // NOI18N
        btnClose1.setMaximumSize(new java.awt.Dimension(50, 50));
        btnClose1.setPreferredSize(new java.awt.Dimension(15, 15));
        btnClose1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClose1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBg1Layout = new javax.swing.GroupLayout(jPanelBg1);
        jPanelBg1.setLayout(jPanelBg1Layout);
        jPanelBg1Layout.setHorizontalGroup(
            jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jPanelBg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelBg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0)
                .addComponent(jPanelBg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBg1Layout.setVerticalGroup(
            jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnClose1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanelBg3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBg2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelBg4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(34, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        // TODO add your handling code here:
        timerGame.cancel();
        BlurPauseGameMultiplayer b = new BlurPauseGameMultiplayer();
        b.setVisible(true);
        ReStartMultiplayer r = new ReStartMultiplayer(b,true,this);
        r.setVisible(true);
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart2ActionPerformed
        // TODO add your handling code here:
        timerCancel();
        BlurPauseGameMultiplayer b = new BlurPauseGameMultiplayer();
        b.setVisible(true);
        AreUSureMultiplayer ars = new AreUSureMultiplayer(b,true,this);
        ars.setVisible(true);
        
    }//GEN-LAST:event_btnStart2ActionPerformed

    private void btnClose1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClose1ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnClose1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public void atualizaPontos(int n, int pontosGanhos){
        if(n == 1){
            atualizaPontosPlayer1(pontosGanhos);
        }
        else{
            atualizaPontosPlayer2(pontosGanhos);
        }
    }
    public void atualizaPontosPlayer1(int pontosGanhos){
        int s = (int) Integer.valueOf(this. JLabelPointsPlayer1.getText())+pontosGanhos;
        JLabelPointsPlayer1.setText(s+"");
        atualizaPlacar();
    }
    public void atualizaPontosPlayer2(int pontosGanhos){
        int s = (int) Integer.valueOf(this. JLabelPointsPlayer2.getText())+pontosGanhos;
        JLabelPointsPlayer2.setText(s+"");
        atualizaPlacar();
    }
    public void atualizaPlacar(){
        if(Integer.valueOf(this. JLabelPointsPlayer1.getText()) >Integer.valueOf(this. JLabelPointsPlayer2.getText())){
            JPanelContainerPointsPlayer1.setColor(Color.BLUE);
            JPanelContainerPointsPlayer1.setBorderColor(Color.BLUE);
            JPanelContainerPointsPlayer2.setColor(new Color(128,128,128));
            JPanelContainerPointsPlayer2.setBorderColor(new Color(128,128,128));
        }
        if(Integer.valueOf(this. JLabelPointsPlayer2.getText()) >Integer.valueOf(this. JLabelPointsPlayer1.getText())){
            JPanelContainerPointsPlayer1.setColor(new Color(128,128,128));
            JPanelContainerPointsPlayer1.setBorderColor(new Color(128,128,128));
            JPanelContainerPointsPlayer2.setColor(Color.BLUE);
            JPanelContainerPointsPlayer2.setBorderColor(Color.BLUE);
            
        }
        if(Objects.equals(Integer.valueOf(this. JLabelPointsPlayer1.getText()), Integer.valueOf(this. JLabelPointsPlayer2.getText()))){
            JPanelContainerPointsPlayer1.setColor(new Color(128,128,128));
            JPanelContainerPointsPlayer1.setBorderColor(new Color(128,128,128));
            JPanelContainerPointsPlayer2.setColor(new Color(128,128,128));
            JPanelContainerPointsPlayer2.setBorderColor(new Color(128,128,128));
        }
        
    }
     public void startGame(int i,int j){
     timerGame = new Timer();
     timerGame.schedule(new MoveGameMultiplayer(tetrisGame1,tetrisGame2,this), i,j);
    }
     public void gameOver(){
         timerGame.cancel();
         //game over tela
     }
     public void timerCancel(){
         timerGame.cancel();
     }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MultiplayerGameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MultiplayerGameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MultiplayerGameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MultiplayerGameMode.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MultiplayerGameMode dialog = new MultiplayerGameMode(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JLabelPointsPlayer1;
    private javax.swing.JLabel JLabelPointsPlayer2;
    private jogotetris.GUI.Componentes.JPanelBg JPanelContainerPointsPlayer1;
    private jogotetris.GUI.Componentes.JPanelBg JPanelContainerPointsPlayer2;
    private jogotetris.GUI.Componentes.BtnClose btnClose1;
    private jogotetris.GUI.Componentes.BtnStart btnStart1;
    private jogotetris.GUI.Componentes.BtnStart btnStart2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg1;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg2;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg3;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg4;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg5;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg6;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg7;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg9;
    private jogotetris.App.TetrisGame tetrisGame1;
    private jogotetris.App.TetrisGame tetrisGame2;
    // End of variables declaration//GEN-END:variables
}
