/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package jogotetris.GUI;

import java.awt.Frame;
import java.awt.geom.RoundRectangle2D;
import jogotetris.Resorses.Blocking;

/**
 *
 * @author senti
 */
public class Settings extends javax.swing.JDialog {
    public ClassicGameMode classic;
    public Frame parent;
    private int theme = 1;
    /**
     * Creates new form Settings
     * @param p
     */
    public Settings(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.parent = parent;
        setLocation(435,187);
        this.setUndecorated(true);
        initComponents();
        setShape(new RoundRectangle2D.Double(0,0,getWidth(), getHeight(),20,20));
        btnSwitch.setSelected(false);
    }
    public Settings(java.awt.Frame parent, boolean modal,ClassicGameMode c) {
        this(parent,modal);
        this.classic = c;
    }
    
    public void Load1(){
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanelBg1 = new jogotetris.GUI.Componentes.JPanelBg();
        jLabel1 = new javax.swing.JLabel();
        btnnBorder1 = new jogotetris.GUI.Componentes.BtnnBorder();
        jPanelBg2 = new jogotetris.GUI.Componentes.JPanelBg();
        jLabel3 = new javax.swing.JLabel();
        btnSwitch = new jogotetris.GUI.Componentes.BtnSwitch();
        jPanelBg3 = new jogotetris.GUI.Componentes.JPanelBg();
        jLabel4 = new javax.swing.JLabel();
        btnSwitch2 = new jogotetris.GUI.Componentes.BtnSwitch();
        jPanelBg4 = new jogotetris.GUI.Componentes.JPanelBg();
        jLabel5 = new javax.swing.JLabel();
        btnSwitch3 = new jogotetris.GUI.Componentes.BtnSwitch();
        jLabel2 = new javax.swing.JLabel();
        jPanelBg5 = new jogotetris.GUI.Componentes.JPanelBg();
        btnStart3 = new jogotetris.GUI.Componentes.BtnStart();
        jPanelBg6 = new jogotetris.GUI.Componentes.JPanelBg();
        btnStart1 = new jogotetris.GUI.Componentes.BtnStart();
        jPanelBg7 = new jogotetris.GUI.Componentes.JPanelBg();
        btnStart2 = new jogotetris.GUI.Componentes.BtnStart();
        btnStart4 = new jogotetris.GUI.Componentes.BtnStart();
        btnStart5 = new jogotetris.GUI.Componentes.BtnStart();
        btnStart6 = new jogotetris.GUI.Componentes.BtnStart();
        btnStart7 = new jogotetris.GUI.Componentes.BtnStart();

        jToggleButton1.setText("jToggleButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(500, 350));
        setResizable(false);

        jPanelBg1.setForeground(new java.awt.Color(228, 229, 214));
        jPanelBg1.setBorderColor(new java.awt.Color(0, 204, 204));
        jPanelBg1.setColor(new java.awt.Color(0, 204, 204));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(228, 229, 214));
        jLabel1.setText("Settings");

        btnnBorder1.setBackground(new java.awt.Color(0, 204, 204));
        btnnBorder1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogotetris/Resorses/x-mark.png"))); // NOI18N
        btnnBorder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnnBorder1ActionPerformed(evt);
            }
        });

        jPanelBg2.setBackground(new java.awt.Color(228, 229, 214));
        jPanelBg2.setBorderColor(new java.awt.Color(228, 229, 214));
        jPanelBg2.setColor(new java.awt.Color(228, 229, 214));
        jPanelBg2.setPreferredSize(new java.awt.Dimension(90, 90));
        jPanelBg2.setRadius(20);

        jLabel3.setFont(new Blocking(15));
        jLabel3.setText("muisc");

        btnSwitch.setBackground(new java.awt.Color(128, 128, 128));
        btnSwitch.setBorder(6);
        btnSwitch.setColorof(new java.awt.Color(0, 174, 255));
        btnSwitch.setRadius(28);

        javax.swing.GroupLayout jPanelBg2Layout = new javax.swing.GroupLayout(jPanelBg2);
        jPanelBg2.setLayout(jPanelBg2Layout);
        jPanelBg2Layout.setHorizontalGroup(
            jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(28, 28, 28))
            .addGroup(jPanelBg2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBg2Layout.setVerticalGroup(
            jPanelBg2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSwitch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanelBg3.setBorderColor(new java.awt.Color(228, 229, 214));
        jPanelBg3.setColor(new java.awt.Color(228, 229, 214));
        jPanelBg3.setPreferredSize(new java.awt.Dimension(90, 90));
        jPanelBg3.setRadius(20);

        jLabel4.setFont(new Blocking(15));
        jLabel4.setText("sound1");

        btnSwitch2.setBackground(new java.awt.Color(128, 128, 128));
        btnSwitch2.setBorder(6);
        btnSwitch2.setColorof(new java.awt.Color(0, 174, 255));
        btnSwitch2.setRadius(28);

        javax.swing.GroupLayout jPanelBg3Layout = new javax.swing.GroupLayout(jPanelBg3);
        jPanelBg3.setLayout(jPanelBg3Layout);
        jPanelBg3Layout.setHorizontalGroup(
            jPanelBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg3Layout.createSequentialGroup()
                .addGroup(jPanelBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBg3Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4))
                    .addGroup(jPanelBg3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSwitch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBg3Layout.setVerticalGroup(
            jPanelBg3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSwitch2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13))
        );

        jPanelBg4.setBorderColor(new java.awt.Color(228, 229, 214));
        jPanelBg4.setColor(new java.awt.Color(228, 229, 214));
        jPanelBg4.setPreferredSize(new java.awt.Dimension(90, 90));
        jPanelBg4.setRadius(20);

        jLabel5.setFont(new Blocking(15));
        jLabel5.setText("sound2");

        btnSwitch3.setBackground(new java.awt.Color(128, 128, 128));
        btnSwitch3.setBorder(6);
        btnSwitch3.setColorof(new java.awt.Color(0, 174, 255));
        btnSwitch3.setRadius(28);

        javax.swing.GroupLayout jPanelBg4Layout = new javax.swing.GroupLayout(jPanelBg4);
        jPanelBg4.setLayout(jPanelBg4Layout);
        jPanelBg4Layout.setHorizontalGroup(
            jPanelBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg4Layout.createSequentialGroup()
                .addGroup(jPanelBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBg4Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5))
                    .addGroup(jPanelBg4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnSwitch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBg4Layout.setVerticalGroup(
            jPanelBg4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(13, 13, 13)
                .addComponent(btnSwitch3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jLabel2.setForeground(new java.awt.Color(228, 229, 214));
        jLabel2.setText("Game theme");

        jPanelBg5.setBorderColor(new java.awt.Color(228, 229, 214));
        jPanelBg5.setColor(new java.awt.Color(228, 229, 214));
        jPanelBg5.setPreferredSize(new java.awt.Dimension(106, 106));
        jPanelBg5.setRadius(20);

        btnStart3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogotetris/Resorses/bb_settings_theme_original.png"))); // NOI18N
        btnStart3.setBorderColor(new java.awt.Color(255, 255, 255));
        btnStart3.setColor(new java.awt.Color(255, 255, 255));
        btnStart3.setColorOver(new java.awt.Color(0, 24, 41));
        btnStart3.setFixColor(new java.awt.Color(255, 255, 255));
        btnStart3.setMaximumSize(new java.awt.Dimension(100, 100));
        btnStart3.setMinimumSize(new java.awt.Dimension(20, 20));
        btnStart3.setPreferredSize(new java.awt.Dimension(60, 60));
        btnStart3.setRadius(20);
        btnStart3.setSizeBorder(30);
        btnStart3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBg5Layout = new javax.swing.GroupLayout(jPanelBg5);
        jPanelBg5.setLayout(jPanelBg5Layout);
        jPanelBg5Layout.setHorizontalGroup(
            jPanelBg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBg5Layout.setVerticalGroup(
            jPanelBg5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart3, javax.swing.GroupLayout.DEFAULT_SIZE, 94, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanelBg6.setBorderColor(new java.awt.Color(228, 229, 214));
        jPanelBg6.setColor(new java.awt.Color(228, 229, 214));
        jPanelBg6.setRadius(20);

        btnStart1.setBackground(new java.awt.Color(255, 255, 255));
        btnStart1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogotetris/Resorses/bb_settings_theme_green.png"))); // NOI18N
        btnStart1.setBorderColor(new java.awt.Color(255, 255, 255));
        btnStart1.setColor(new java.awt.Color(255, 255, 255));
        btnStart1.setFixColor(new java.awt.Color(255, 255, 255));
        btnStart1.setPreferredSize(new java.awt.Dimension(100, 100));
        btnStart1.setRadius(20);
        btnStart1.setSizeBorder(30);
        btnStart1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBg6Layout = new javax.swing.GroupLayout(jPanelBg6);
        jPanelBg6.setLayout(jPanelBg6Layout);
        jPanelBg6Layout.setHorizontalGroup(
            jPanelBg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelBg6Layout.setVerticalGroup(
            jPanelBg6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanelBg7.setBorderColor(new java.awt.Color(228, 229, 214));
        jPanelBg7.setColor(new java.awt.Color(228, 229, 214));
        jPanelBg7.setRadius(20);

        btnStart2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jogotetris/Resorses/bb_settings_theme_white.png"))); // NOI18N
        btnStart2.setBorderColor(new java.awt.Color(255, 255, 255));
        btnStart2.setColor(new java.awt.Color(255, 255, 255));
        btnStart2.setColorOver(new java.awt.Color(102, 102, 102));
        btnStart2.setFixColor(new java.awt.Color(255, 255, 255));
        btnStart2.setPreferredSize(new java.awt.Dimension(100, 100));
        btnStart2.setRadius(20);
        btnStart2.setSizeBorder(30);
        btnStart2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBg7Layout = new javax.swing.GroupLayout(jPanelBg7);
        jPanelBg7.setLayout(jPanelBg7Layout);
        jPanelBg7Layout.setHorizontalGroup(
            jPanelBg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelBg7Layout.setVerticalGroup(
            jPanelBg7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg7Layout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(btnStart2, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnStart4.setBorderColor(new java.awt.Color(0, 204, 204));
        btnStart4.setColor(new java.awt.Color(204, 0, 0));
        btnStart4.setColorOver(new java.awt.Color(0, 0, 0));
        btnStart4.setFixColor(new java.awt.Color(255, 255, 255));
        btnStart4.setMaximumSize(new java.awt.Dimension(70, 70));
        btnStart4.setMinimumSize(new java.awt.Dimension(10, 10));
        btnStart4.setPreferredSize(new java.awt.Dimension(10, 10));
        btnStart4.setRadius(12);
        btnStart4.setSizeBorder(10);
        btnStart4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart4ActionPerformed(evt);
            }
        });

        btnStart5.setBorderColor(new java.awt.Color(0, 204, 204));
        btnStart5.setColor(new java.awt.Color(0, 0, 0));
        btnStart5.setColorOver(new java.awt.Color(0, 0, 0));
        btnStart5.setMinimumSize(new java.awt.Dimension(10, 10));
        btnStart5.setPreferredSize(new java.awt.Dimension(10, 10));
        btnStart5.setRadius(20);
        btnStart5.setSizeBorder(5);
        btnStart5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart5ActionPerformed(evt);
            }
        });

        btnStart6.setBorderColor(new java.awt.Color(0, 204, 204));
        btnStart6.setColor(new java.awt.Color(0, 204, 204));
        btnStart6.setColorOver(new java.awt.Color(0, 0, 0));
        btnStart6.setMinimumSize(new java.awt.Dimension(10, 10));
        btnStart6.setPreferredSize(new java.awt.Dimension(10, 10));
        btnStart6.setRadius(20);
        btnStart6.setSizeBorder(5);
        btnStart6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart6ActionPerformed(evt);
            }
        });

        btnStart7.setText("save");
        btnStart7.setBorderColor(new java.awt.Color(0, 24, 41));
        btnStart7.setColorOver(new java.awt.Color(0, 24, 41));
        btnStart7.setFixColor(new java.awt.Color(0, 24, 41));
        btnStart7.setFont(new Blocking(20));
        btnStart7.setRadius(10);
        btnStart7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStart7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelBg1Layout = new javax.swing.GroupLayout(jPanelBg1);
        jPanelBg1.setLayout(jPanelBg1Layout);
        jPanelBg1Layout.setHorizontalGroup(
            jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg1Layout.createSequentialGroup()
                        .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanelBg5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanelBg1Layout.createSequentialGroup()
                                .addComponent(jPanelBg2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStart4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                        .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBg1Layout.createSequentialGroup()
                                .addComponent(jPanelBg3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStart5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanelBg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(70, 70, 70)
                        .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBg1Layout.createSequentialGroup()
                                .addGap(70, 70, 70)
                                .addComponent(btnnBorder1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBg1Layout.createSequentialGroup()
                                .addComponent(jPanelBg4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnStart6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btnStart7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jPanelBg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(28, 28, 28))
                    .addGroup(jPanelBg1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanelBg1Layout.setVerticalGroup(
            jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBg1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelBg1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jPanelBg3, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelBg1Layout.createSequentialGroup()
                        .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnnBorder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanelBg4, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnStart6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jPanelBg2, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE)
                                .addComponent(btnStart4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(btnStart5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelBg1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanelBg5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBg6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanelBg7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnStart7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        jPanelBg1Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jPanelBg2, jPanelBg3});

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBg1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnStart1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart1ActionPerformed
        // TODO add your handling code here:
         setTheme(2);
        
    }//GEN-LAST:event_btnStart1ActionPerformed

    private void btnnBorder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnnBorder1ActionPerformed
        // TODO add your handling code here:
        classic.startGame(1000, 1000);
        parent.dispose();
        this.dispose();
    }//GEN-LAST:event_btnnBorder1ActionPerformed

    private void btnStart2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart2ActionPerformed
        // TODO add your handling code here:
         setTheme(3);
    }//GEN-LAST:event_btnStart2ActionPerformed

    private void btnStart3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart3ActionPerformed
        // TODO add your handling code here:
        setTheme(1);
    }//GEN-LAST:event_btnStart3ActionPerformed

    private void btnStart4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart4ActionPerformed
        // TODO add your handling code here:
        if(this.btnSwitch.isSelected()){
            classic.stopMusic();
        }
        else{
            classic.playMusic(0);
        }
    }//GEN-LAST:event_btnStart4ActionPerformed
    public  void setTheme(int theme){
        this.theme = theme;
    }
    public void changeTheme(){
        switch(this.getTheme()){
            case 1:
            classic.Changeteme1();
            break;
            case 2:
            classic.Changeteme2();
            break;
            case 3:
            classic.Changeteme3();
            break;          
        }
    }
   
    private void btnStart5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart5ActionPerformed
        // TODO add your handling code here:
        classic.setCanPlaySE(!(btnSwitch2.isSelected()));
    }//GEN-LAST:event_btnStart5ActionPerformed

    private void btnStart6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart6ActionPerformed
        // TODO add your handling code here:
        classic.setCanPlaySEBoard(!(btnSwitch3.isSelected()));
    }//GEN-LAST:event_btnStart6ActionPerformed

    private void btnStart7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStart7ActionPerformed
        // TODO add your handling code here:
        Save();
    }//GEN-LAST:event_btnStart7ActionPerformed
    public void Save(){
        if(this.btnSwitch.isSelected()){
            classic.stopMusic();
        }
        else{
            classic.playMusic(0);
        }
        classic.setCanPlaySE(!(btnSwitch2.isSelected()));
        classic.setCanPlaySEBoard(!(btnSwitch3.isSelected()));
        changeTheme();
        classic.startGame(1000, 1000);
        this.dispose();
    }
    public boolean getSwitch1(){
        return btnSwitch.isSelected();
    }
    public void setSwitch1(boolean modal){
        btnSwitch.setSelected(modal);
    }
    public boolean getCanPlaySE1(){
        return !(btnSwitch2.isSelected());
    }
    public void setCanPlaySE1(boolean modal){
        btnSwitch2.setSelected(modal);
    }
    public boolean getCanPlaySE2(){
        return !(btnSwitch3.isSelected());
    }
    public void setCanPlaySE2(boolean modal){
        btnSwitch3.setSelected(modal);
    }        /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Settings.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Settings dialog = new Settings(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private jogotetris.GUI.Componentes.BtnStart btnStart1;
    private jogotetris.GUI.Componentes.BtnStart btnStart2;
    private jogotetris.GUI.Componentes.BtnStart btnStart3;
    private jogotetris.GUI.Componentes.BtnStart btnStart4;
    private jogotetris.GUI.Componentes.BtnStart btnStart5;
    private jogotetris.GUI.Componentes.BtnStart btnStart6;
    private jogotetris.GUI.Componentes.BtnStart btnStart7;
    private jogotetris.GUI.Componentes.BtnSwitch btnSwitch;
    private jogotetris.GUI.Componentes.BtnSwitch btnSwitch2;
    private jogotetris.GUI.Componentes.BtnSwitch btnSwitch3;
    private jogotetris.GUI.Componentes.BtnnBorder btnnBorder1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg1;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg2;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg3;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg4;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg5;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg6;
    private jogotetris.GUI.Componentes.JPanelBg jPanelBg7;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the theme
     */
    public int getTheme() {
        return theme;
    }
}
